spring:
  profiles:
    active: dev

---
#dev
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 81

---
#prod
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 80
