spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: root

---
#dev
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 81

---
#prod
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 80
